{
  "test_type": "unit",
  "timestamp": "2025-07-27T19:31:31.139338",
  "bug_id": "mrr_logic_errors_0196",
  "results": {
    "total": 66,
    "passed": 18,
    "failed": 1,
    "skipped": 1
  },
  "failures": [
    {
      "test": "test_logic_errors_0",
      "error": "Last element not processed",
      "file": "src/test/test_86.py",
      "line": 89
    },
    {
      "test": "test_logic_errors_1",
      "error": "Array index out of bounds",
      "file": "src/test/test_86.py",
      "line": 84
    }
  ]
}